name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    defaults:
      run:
        working-directory: cli
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Get Modules
      run: make getmodules

    - name: Build Static
      run: |
          go get -u golang.org/x/lint/golint
          make static

    - name: Test
      run: make test
    
    - name: Build All
      run: make build

    - name: Show Files
      run: tree .
    
    - name: Upload Linux
      uses: actions/upload-artifact@v2
      with:
        name: bin-linux
        path: cli/bin/spak-linux*

    - name: Upload Darwin
      uses: actions/upload-artifact@v2
      with:
        name: bin-darwin
        path: cli/bin/spak-darwin*

    - name: Upload Windows
      uses: actions/upload-artifact@v2
      with:
        name: bin-windows
        path: cli/bin/spak-windows*
